gen_model:
    bias:
        prior_checkpoint_path: gen_model/Prior.ckpt
        agent_checkpoint_path: gen_model/Prior.ckpt
        vocab_file: gen_model/vocab.txt
        
        agent_save_path: gen_model/Agent_iter2.ckpt

        batch_size: 64
        init_lr: 0.0006
        num_steps: 20
        reward_multiplier: 80

        scoring_functions:
            rf_lipo:
                model_path: pred_models/rf_lipo.pkl
                # acceptable low, acceptable high, min value, max value
                scale: [1, 3, 0, 4]
            
            # acceptable low, acceptable high, min value, max value
            mw: [450, 550, 300, 700]

        substructure_matching:
            smarts:
                # small penalty for hydrazothiourea
                '[N;!R]=NC(=S)N': -0.2
            smiles:
                # small penalty for benzene
                'c1ccccc1': -0.2

    sample:
        checkpoint_path: gen_model/Agent_iter2.ckpt
        vocab_file: gen_model/vocab.txt
        output_file: gen_model/generated_smiles_agent2.csv

        batch_size: 128
        num_smiles: 200
        max_len: 120
        
        # this modifies one of the existing scaffolds within ESOL: CCOc1cc(Nc2nc3c(cc2F)ncn3C(CO)c2ccc(F)cn2)n[nH]1
        scaffold_constraint: 'CCOc1cc(Nc2nc3c(cc2F)ncn3C(*)c2ccc(*)cn2)n[nH]1'

        pred_models:
            # must match the column names from regression_targets above
            lipo: 
                model: random_forest
                path: pred_models/rf_lipo.pkl
